export const INDIVIDUAL_INPUTS = [
  {
    id: 1,
    label: 'Email',
    name: 'email',
    placeholder: 'Enter your Email',
    type: 'email',
    error: 'Email is required',
  },
  {
    id: 2,
    label: 'First Name',
    name: 'firstName',
    placeholder: 'Enter your First Name',
    type: 'text',
    error: 'First name is required',
  },
  {
    id: 3,
    label: 'Last Name',
    name: 'lastName',
    placeholder: 'Enter your Last Name',
    type: 'text',
    error: 'Last name is required',
  },
  {
    id: 4,
    label: 'Password',
    name: 'password',
    placeholder: 'Enter your Password',
    type: 'password',
    error: 'Password is required',
  },
  {
    id: 5,
    label: 'Phone',
    name: 'phone',
    placeholder: 'Enter your Phone',
    type: 'phone',
    error: 'Phone is required',
  },
  {
    id: 6,
    label: 'Birthdate',
    name: 'birthdate',
    placeholder: 'Select date',
    type: 'date',
    error: 'Birthdate is required',
  },
  {
    id: 7,
    label: 'Gender',
    name: 'gender',
    placeholder: 'Select Gender',
    type: 'list',
    options: [
      { id: 1, label: 'Male', value: 'male' },
      { id: 2, label: 'Female', value: 'female' },
    ],
    error: 'Gender is required',
  },
  {
    id: 8,
    label: 'Address',
    name: 'address',
    placeholder: 'Enter your address',
    type: 'text',
    error: 'Address is required',
  },
];

export const BUSINESS_INPUTS = [
  {
    id: 1,
    label: 'Email',
    name: 'email',
    placeholder: 'Enter your Email',
    type: 'email',
    error: 'Email is required',
  },
  {
    id: 2,
    label: 'First Name',
    name: 'firstName',
    placeholder: 'Enter your First Name',
    type: 'text',
    error: 'First name is required',
  },
  {
    id: 3,
    label: 'Last Name',
    name: 'lastName',
    placeholder: 'Enter your Last Name',
    type: 'text',
    error: 'Last name is required',
  },
  {
    id: 4,
    label: 'Password',
    name: 'password',
    placeholder: 'Enter your Password',
    type: 'password',
    error: 'Password is required',
  },
  {
    id: 5,
    label: 'Phone',
    name: 'phone',
    placeholder: 'Enter your Phone',
    type: 'phone',
    error: 'Phone is required',
  },
  {
    id: 6,
    label: 'Country',
    name: 'country',
    placeholder: 'Select Country',
    type: 'list',
    error: 'Country is required',
    options: [],
  },
  {
    id: 8,
    label: 'City',
    name: 'city',
    placeholder: 'Select City',
    type: 'list',
    error: 'City is required',
    options: [],
  }
];
